version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
    networks:
      - my_network

  usuarios_backend:
    build: ./usuarios
    container_name: usuarios_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./usuarios:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/usuarios_db
    networks:
      - my_network

  clientes_backend:
    build: ./clientes
    container_name: clientes_backend
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./clientes:/app
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/clientes_db
    networks:
      - my_network

  proveedores_backend:
    build: ./proveedores
    container_name: proveedores_backend
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./proveedores:/app
    ports:
      - "8002:8002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/proveedores_db
    networks:
      - my_network

  productos_servicios_backend:
    build: ./productos_servicios
    container_name: productos_servicios_backend
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ./productos_servicios:/app
    ports:
      - "8003:8003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/productos_servicios_db
    networks:
      - my_network

  facturacion_backend:
    build: ./facturacion
    container_name: facturacion_backend
    command: python manage.py runserver 0.0.0.0:8004
    volumes:
      - ./facturacion:/app
    ports:
      - "8004:8004"
    depends_on:
      - clientes_backend
      - productos_servicios_backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/facturacion_db
    networks:
      - my_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - usuarios_backend
      - clientes_backend
      - proveedores_backend
      - productos_servicios_backend
      - facturacion_backend
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
